version: "3.7"
volumes:
  kitchen-fore-dbdata:
services:
  kitchen-force-db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: kitchen-force-db
    ports:
      - "3311:3306"
    environment:
      - MYSQL_DATABASE=kitchen
      - MYSQL_USER=kitchenuser
      - MYSQL_PASSWORD=kitchen
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - kitchen-fore-dbdata:/var/lib/mysql8